/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //apiSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'TAC',
      items: ['Level 1/tactools','Level 1/sop','Level 1/transfers','Level 1/resources','Level 1/legacy-links'],
    },
    {
      type: 'link',
      label: 'TAC Workflow v1.15', // The link label
      href: 'http://knowledge.dsl.net.pk/TAC%20L1%20TroubleShooting%20Guide%20V%201.15.docx', // The external URL
    },
    {
      type: 'doc',
      id: 'Level 1/whatsapp', // document ID
      label: 'Whatsapp Templates', // sidebar label
    },
    {
      type: 'category',
      label: 'Video',
      items: ['Level 1/basic','Level 1/digital','Level 1/joy', 'Level 1/nwatch'],
    },
    {
      type: 'category',
      label: 'NGN',
      items: ['Level 1/voip', 'Level 1/pots'],
    },
    {
      type: 'category',
      label: 'Core',
      items: ['Level 1/l2vpn', 'Level 1/optimus', 'Level 1/speedup', 'Level 1/bras', 'Level 1/additional_usage', 'Level 1/microtik'],
    },
    {
      type: 'category',
      label: 'Systems',
      items: ['Level 1/eview'],
    },
    {
      type: 'category',
      label: 'NOC',
      items: ['Level 1/noc'],
    },
    {
      type: 'link',
      label: 'Employee Handbook', // The link label
      href: 'https://drive.google.com/file/d/1yusHlAuYFDjdajiVlfXzGtVsUhSXIKUq/view', // The external URL
    },
    // External link
    {
      type: 'link',
      label: 'CRM', // The link label
      href: 'https://crm.nayatel.com', // The external URL
    },
    {
      type: 'link',
      label: 'Queue', // The link label
      href: 'http://172.21.22.142:8080/queuemetrics/qm/realtime2_frame.jsp', // The external URL
    },
    {
      type: 'link',
      label: 'Mail', // The link label
      href: 'https://mail.nayatel.com', // The external URL
    },
    {
      type: 'link',
      label: 'NCE', // The link label
      href: 'https://nce.nayatel.com:31943/unisso/login.action?service=%2Funisess%2Fv1%2Fauth%3Fservice%3D%252Fnmsnetworkmgrwebsite%252Fv1%252Fwebswing%252Findexforwebswing.html#page=RlBPUC00LTEoMTcyLjE2LjEzLjk4KSUyNiUyNmlzU3dpbmdPcGVuJTI2JTI2MTY=', // The external URL
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'Access TAC',
      items: ['access_ngn'],
    },
  ],
  systemSidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'systems',
    },
    {
      type: 'category',
      label: 'Web Hosting',
      items: ['System TAC/basics', 'System TAC/cpanel', 'System TAC/dns', 'System TAC/ssl'],
    },
    {
      type: 'category',
      label: 'Mail Hosting',
      items: ['System TAC/mail_basics','System TAC/mail_infra','System TAC/mail_issues','System TAC/mail_tools'],
    },
    {
      type: 'category',
      label: 'Nwall',
      items: ['System TAC/nwall start'],
    },
    {
      type: 'link',
      label: 'Statuspage', // The link label
      href: 'https://stats.uptimerobot.com/qXEK3u1m61', // The external URL
    },
  ],
};

module.exports = sidebars;
