/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //apiSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  

  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'TAC',
      items: ['Level 1/tactools','Level 1/sop','Level 1/transfers','Level 1/resources','Level 1/legacy-links'],
    },
    {
      type: 'doc',
      id: 'Level 1/whatsapp', // document ID
      label: 'Whatsapp Templates', // sidebar label
    },
    {
      type: 'category',
      label: 'Video',
      items: ['Level 1/basic','Level 1/digital','Level 1/joy', 'Level 1/nwatch'],
    },
    {
      type: 'category',
      label: 'NGN',
      items: ['Level 1/voip', 'Level 1/pots'],
    },
    {
      type: 'category',
      label: 'Core',
      items: ['Level 1/l2vpn', 'Level 1/optimus', 'Level 1/speedup', 'Level 1/bras', 'Level 1/additional_usage', 'Level 1/microtik'],
    },
    {
      type: 'category',
      label: 'Systems',
      items: ['Level 1/eview'],
    },
    {
      type: 'category',
      label: 'NOC Files',
      items: ['Level 1/noc'],
    },
    {
      type: 'link',
      label: 'TAC Workflow v1.15', // The link label
      href: 'https://drive.google.com/uc?export=download&id=1K7J8El8RcCwEPl-lIxWu8-ZR_Ggio44-', // The external URL
    },
    {
      type: 'link',
      label: 'Employee Handbook v4.3', // The link label
      href: 'https://drive.google.com/uc?export=download&id=1gC97yvWETdI70t-NNmda1xsCFflrNnzH', // The external URL
    },
    {
      type: 'link',
      label: 'TAC Guidelines v1.8', // The link label
      href: 'https://drive.google.com/uc?export=download&id=1K7J8El8RcCwEPl-lIxWu8-ZR_Ggio44-', // The external URL
    },
    // External link
    {
      type: 'link',
      label: 'CRM', // The link label
      href: 'https://crm.nayatel.com', // The external URL
    },
    {
      type: 'link',
      label: 'Queue', // The link label
      href: 'http://172.21.22.142:8080/queuemetrics/qm/realtime2_frame.jsp', // The external URL
    },
    {
      type: 'link',
      label: 'Mail', // The link label
      href: 'https://mail.nayatel.com', // The external URL
    },
    {
      type: 'link',
      label: 'Ndoctor Emulator', // The link label
      href: 'https://knowledge.dsl.net.pk/Ndoctor/index.html', // The external URL
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'Access TAC',
      items: ['access_ngn'],
    },
  ],
  systemSidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'systems',
    },
    {
      type: 'category',
      label: 'Web Hosting',
      items: ['System TAC/basics', 'System TAC/cpanel', 'System TAC/dns', 'System TAC/ssl'],
    },
    {
      type: 'category',
      label: 'Mail Hosting',
      items: ['System TAC/mail_basics','System TAC/mail_infra','System TAC/mail_issues','System TAC/mail_tools'],
    },
    {
      type: 'category',
      label: 'Nwall',
      items: ['System TAC/nwall start'],
    },
    {
      type: 'link',
      label: 'Statuspage', // The link label
      href: 'https://stats.uptimerobot.com/qXEK3u1m61', // The external URL
    },
    {
      type: 'link',
      label: 'System Manuals', // The link label
      href: 'https://drive.google.com/drive/folders/1Iw0NKuJneexJmTrr3j4-Qz1NF-zR6Dxq', // The external URL
    },
    
  ],
};

module.exports = sidebars;
