/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //apiSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  

  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'TAC',
      items: ['Level 1/tactools','Level 1/sop','Level 1/transfers','Level 1/resources','Level 1/legacy-links'],
    },
    {
      type: 'doc',
      id: 'Level 1/whatsapp', // document ID
      label: 'Whatsapp Templates', // sidebar label
    },
    {
      type: 'category',
      label: 'Video',
      items: ['Level 1/basic','Level 1/digital','Level 1/joy', 'Level 1/nwatch'],
    },
    {
      type: 'category',
      label: 'NGN',
      items: ['Level 1/voip', 'Level 1/pots'],
    },
    {
      type: 'category',
      label: 'Core',
      items: ['Level 1/l2vpn', 'Level 1/optimus', 'Level 1/speedup', 'Level 1/bras', 'Level 1/additional_usage', 'Level 1/microtik'],
    },
    {
      type: 'category',
      label: 'Systems',
      items: ['Level 1/eview'],
    },
    {
      type: 'category',
      label: 'NOC Files',
      items: ['Level 1/noc'],
    },
    {
      type: 'link',
      label: 'Email Configuration', // The link label
      href: 'https://drive.google.com/uc?export=download&id=1-hLtyfNKZy5mq2W5v3j5bT6nw4tMVkSY', // The external URL
    },
    {
      type: 'link',
      label: 'TAC Workflow v1.15', // The link label
      href: 'https://drive.google.com/uc?export=download&id=1K7J8El8RcCwEPl-lIxWu8-ZR_Ggio44-', // The external URL
    },
    {
      type: 'link',
      label: 'Employee Handbook v4.3', // The link label
      href: 'https://drive.google.com/uc?export=download&id=1gC97yvWETdI70t-NNmda1xsCFflrNnzH', // The external URL
    },
    {
      type: 'link',
      label: 'TAC Guidelines v1.8', // The link label
      href: 'https://drive.google.com/uc?export=download&id=1K7J8El8RcCwEPl-lIxWu8-ZR_Ggio44-', // The external URL
    },
    // External link
    {
      type: 'link',
      label: 'CRM', // The link label
      href: 'https://crm.nayatel.com', // The external URL
    },
    {
      type: 'link',
      label: 'Queue', // The link label
      href: 'http://172.21.22.142:8080/queuemetrics/qm/realtime2_frame.jsp', // The external URL
    },
    {
      type: 'link',
      label: 'Mail', // The link label
      href: 'https://mail.nayatel.com', // The external URL
    },
    {
      type: 'link',
      label: 'Ndoctor Emulator', // The link label
      href: 'https://knowledge.dsl.net.pk/Ndoctor/index.html', // The external URL
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'Access TAC',
      items: ['access_ngn'],
    },
    {
      type: 'link',
      label: 'Commands HuaweiOLT/ BRAS/ ASR Feb2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/HuaweiOLT+BRAS+ASR_Commands_Feb2021.txt', // The external URL
    },
    {
      type: 'link',
      label: 'POTS_passwords_NGN', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/POTS_passwords_NGN.xlsx', // The external URL
    },
    {
      type: 'link',
      label: 'Egresses_Ports_Sep2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Master%20Egress%20Ports_Sep2021.xlsx', // The external URL
    },
    {
      type: 'link',
      label: 'Equipment Retrieval Manual Feb2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_Equipment_Retrieval_Feb2021.docx', // The external URL
    },
    {
      type: 'link',
      label: 'Training Access-NGN TAC Feb2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_Training_Access-NGN%20TAC_Feb2021.docx', // The external URL
    },
    {
      type: 'link',
      label: 'Troubleshooting Access-NGN TAC V2.0 Feb2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_Troubleshooting_Access-NGN%20TAC_V2.0_Feb2021.docx', // The external URL
    },
    {
      type: 'link',
      label: 'Installation Manual June2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_Installation_June2021.docx', // The external URL
    },
    {
      type: 'link',
      label: 'CVAS Installation 2020', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_CVAS_Installation_2020.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Installation Checklist_March2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Installation_Checklist_March2021.xlsx', // The external URL
    },
    {
      type: 'link',
      label: 'N-watch Troubleshooting 2020', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_N-watch_Troubleshooting_2020.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'POTS Troubleshooting 2020', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_POTS_Troubleshooting_2020.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Manual Service Port Plotting 2020', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_Service_Port_Plotting_2020.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Custom Line Profile Cases', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Custom_Line_Profile_Cases_2020.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Manual HOSTEX Extensions Creation BICOM_2018', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_HOSTEX_Extensions_Creation_BICOM_2018.PDF', // The external URL
    },
    {
      type: 'link',
      label: 'Manual ATA Cisco SPA112 2-port_2018', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_ATA_Cisco_SPA112_2-port_2018.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Manual ATA D-link DVG-2102S 2-port_2018', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_ATA_D-link_DVG-2102S_2-port_2018.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Manual ATA D-link DVG-5102S 2-port_2021', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_ATA_D-link_DVG-5102S_2-port_2021.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Manual ATA Linksys SPA8000 8-port_2018', // The link label
      href: 'http://knowledge.dsl.net.pk/Access-NGN%20TAC_Manuals/Manual_ATA_D-link_DVG-2102S_2-port_2018.pdf', // The external URL
    },
    
    {
      type: 'link',
      label: 'CloudPBX Access Configuration Manual_final', // The link label
      href: 'http://knowledge.dsl.net.pk/CloudPBX%20Access%20Configuration%20Manual_final.pdf', // The external URL
    },
    {
      type: 'link',
      label: 'Extenstion Script (Cisco SPA112)', // The link label
      href: 'http://knowledge.dsl.net.pk/ABC.csv', // The external URL
    },
    {
      type: 'link',
      label: 'ATCA SoftScript', // The link label
      href: 'http://knowledge.dsl.net.pk/ATCA%20SoftScript%20v%201.1.xlsx', // The external URL
    },


  ],
  systemSidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'systems',
    },
    {
      type: 'category',
      label: 'Web Hosting',
      items: ['System TAC/basics', 'System TAC/cpanel', 'System TAC/dns', 'System TAC/ssl'],
    },
    {
      type: 'category',
      label: 'Mail Hosting',
      items: ['System TAC/mail_basics','System TAC/mail_infra','System TAC/mail_issues','System TAC/mail_tools'],
    },
    {
      type: 'category',
      label: 'Nwall',
      items: ['System TAC/nwall start'],
    },
    {
      type: 'link',
      label: 'Statuspage', // The link label
      href: 'https://nayatel.betteruptime.com', // The external URL
    },
    {
      type: 'link',
      label: 'System Manuals', // The link label
      href: 'https://drive.google.com/drive/folders/1Iw0NKuJneexJmTrr3j4-Qz1NF-zR6Dxq', // The external URL
    },
    
  ],
};

module.exports = sidebars;
